spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alquiler_prendas?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate   # usando tu DDL (recomendado)
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8080